version: '3.3'

services:
  app:
    build: .
    ports:
      - "8082:8082"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=coursemanagement

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: coursemanagement
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./create_table.sql:/docker-entrypoint-initdb.d/create_table.sql

volumes:
  mysql-data:
